### ISSUE TITLE
Add button logic

### ISSUE THREAD

**Issue by da-manifest** [Orderella/PopupDialog#102]
Hi,
is it possible to add some logic to buttons? For example I created custom popup dialog containing textfield. Is it possible to disable/enable buttons depending on textfield text?
Thanks

**Comment by mwfire** [comment]
Hey @da-manifest,

You can always pass a reference to PopupDialog to your custom view controller, same is true for single buttons. Just make sure the references are weak in order to prevent retain cycles.

One way would be to create the dialog as follows:

```
// Instantiate your custom view controller
let vc = YourCustomViewController(...)

// Instantiate the popup dialog
let popup = PopupDialog(viewController: vc, gestureDismissal: false) {
  ...
}

// Create and add popup buttons
let cancel = DefaultButton(title: "Cancel") {
    ...
}

let continue = DefaultButton(title: "Continuel") {
    ...
}
popup.addButtons([cancel, continue])

// Add a reference to the continue button to your custom view controller
vc.continueButton = continue

// Last but not least: present the PopupDialog
present(popup, animated: true, completion: nil)
```

In your custom view controller, you would have to have a property continueButton:

```
weak var continueButton: PopupDialogButton?
```

Now you can enable or disable the button anywhere from your custom view controller

```
continueButton?.enabled = false
```

This is untested, hope it helps :)

**Comment by da-manifest** [comment]
Thanks for your answer, I'll try this. 
For now I used NotificationCenter, works fine but, I think, it's more complicated then your solution :)
