### ISSUE TITLE
Custom view pop not appearing ? 

### ISSUE THREAD

**Issue by fadylateef** [Orderella/PopupDialog#118]
Using
Xcode 8.0 ,
Swift 3 ,
Popupdialog last repo .

------------------------------
I am using popupdialog to show custom .xib view, it works great first time but If i made any changes to size or autolayout contraints it shows nothing . 

Also, I made edits on the example , I've changed the size of .xib view and then it showed nothing too .

Thanks in advance for gr8 library

**Comment by mwfire** [comment]
Hey @fadylateef,

in order to display content views correctly, all constraints have to be satisfied. In particular, height has to be set correctly. As this cannot be debugged remotely:
- Do you get any auto layout related console logs?
- Can you attach a sample project that showcases your use case?

Thanks!

**Comment by mwfire** [comment]
Closed due to missing feedback

**Comment by fitsyu** [comment]
Hi all!
I'm also troubled with this problem. I made a view that centered in the root view and set its size a half of the root view. After debugging the view in Xcode 8, I found that the view height is 0.
<img width="944" alt="screen shot 2017-03-22 at 8 38 51 pm" src="https://cloud.githubusercontent.com/assets/5017610/24200611/32007b6a-0f40-11e7-8706-66cb9707b5b4.png">

I believe this because UIView has no default intrinsic size.
Should I try giving fixed height constraint?

**Comment by mwfire** [comment]
Hi @fitsyu,

make sure to lay out all constraints so the height is defined by the constraints themselves, just like in the pseudo layout below. Make sure to give your views heights unless they are labels etc.

 ____
   |
[view(50)]
   |
[view(120)]
   | 
 ____

Hope that helps!

**Comment by smemamian** [comment]
View
    View [fixed height and width]
       my image views [fixed height and width]
Solved:

<img width="894" alt="screen shot 2017-03-31 at 12 35 04" src="https://cloud.githubusercontent.com/assets/2825656/24541866/9a75baf0-160e-11e7-9bbb-111447a7e461.png">
