### ISSUE TITLE
How can I make PopupDialog with custom view controller and view of custom view controller should be loaded from storyboard file ?

### ISSUE THREAD

**Issue by krishnameena** [Orderella/PopupDialog#152]
I am trying but view is not getting loaded.

![simulator screen shot 11-jul-2017 1 20 53 pm](https://user-images.githubusercontent.com/10487399/28058923-f6416be6-663f-11e7-964c-cd5a4123a9cf.png)

**Comment by mwfire** [comment]
Hi @krishnameena,

did you have a look at the examples folder? The star rating view controller is a custom view controller, maybe it helps you achieving what you want.

One thing to make sure: All necessary top to bottom constraints need to be defined, otherwise view controllers will not appear.

Hope that helps
Martin

**Comment by Abhishekl90** [comment]
@krishnameena Did you manage to solve this issue, coz I am facing with the same.
This is my code

        func openPopup() {
        let customPopup = PopupViewController(nibName: nil,bundle: nil)
        let popup = PopupDialog(viewController: customPopup,transitionStyle: 
        .bounceUp,gestureDismissal: false)
        customPopup.popup = popup
        
        // Present dialog
        present(popup, animated: true, completion: nil)
    
    }

I have been referring to example,
If the issue is solved what should be done to make the Popup visible

**Comment by krishnameena** [comment]
Still I am facing the issue

**Comment by jboisjo** [comment]
i got the same issue!

**Comment by jboisjo** [comment]
i found the issue guys, it's really with the constraint. Make sure you have height and width constraint set up otherwise the view will never show...

<img width="262" alt="screen shot 2017-07-26 at 1 15 15 pm" src="https://user-images.githubusercontent.com/18666345/28634225-857f0b2c-7204-11e7-966f-03eef48605f1.png">

make sure you have every side also...

**Comment by laoyur** [comment]
@jboisjo your snapshot shows the constraints of the subview of the root view ?
could you please provide more detailed info, or upload a working sample project ? thanks

**Comment by laoyur** [comment]
ok, I figured out the problem.
for example:
1. drag a UIViewController onto your storyboard
2. drag a UITextView onto the root view
3. add proper constraints to your UITextView
4. add explicit height + weight constraints to your UITextView
5. run your code and it will work like a charm

**Comment by mwfire** [comment]
Also discussed in https://github.com/Orderella/PopupDialog/issues/164

**Comment by lankonyue** [comment]
Hi @mwfire I'm also facing the same issue. I compared **MyViewController** and **RatingViewController**, the only difference is: the root view of **RatingViewController** has four constraints, but I can not add any constraints to the root view of **MyViewController**, in my xib with Xcode 9.4.

So I want to ask you how to add the constraints for the root view of **UIViewController**, hope you can help me, thank you very much.

RatingViewController Contraints Screenshot:
![ScreenShot1](https://raw.githubusercontent.com/FlyingArcher/MyShareFiles/master/Files/RatingViewController%20AutoLayout.png)

RatingViewController Contraints Screenshot:
![ScreenShot2](https://github.com/FlyingArcher/MyShareFiles/raw/master/Files/MyViewController%20AutoLayout.png)
