### ISSUE TITLE
status bar always return back when showing PopupDialog because returnpreferredStatusBarStyle in PopupDialog class don't allow override

### ISSUE THREAD

**Issue by nghiaiosdev** [Orderella/PopupDialog#195]

**Comment by mwfire** [comment]
Hey there! Did you set hideStatusBar to true in the dialog initializer?

**Comment by juliensaad** [comment]
Hey @mwfire, I'm encountering this issue too. The problem is that the status bar is only hidden in `viewDidAppear`, so even setting `hideStatusBar` to true means that the status bar will be shown before `viewDidAppear` is called. The bar is then hidden after a 0.15s animation, but it still is clearly visible for that period of time.

**Comment by dilpreetsingh** [comment]
Hey @mwfire, like @juliensaad said, this is still an issue. The status bar is hidden by my view-controller but when I show a popup dialog (initialised with `hideStatusBar` set to true) I see the status bar flicker in and then animate out.
This is likely because the hide/show code for status bar is in `viewDidAppear`, can this be moved to `viewWillAppear`?
