### ISSUE TITLE
Custom general dialog with UITableView, scale to fit up to max?

### ISSUE THREAD

**Issue by kehollin** [Orderella/PopupDialog#233]
> Please fill out this template when filing an issue.
> All ℹ symbols should be replaced with information on the issue.
> Please remove this line and all above before submitting.

# Report
Wondering if there's some sort of support for a variable height table view. For example, if the view takes two items I'd like it to be just tall enough to hold both items. If on the other hand there are 50 items I'd like the view to max out at a certain height, ideally proportional to the screen (i.e. 70%). As a bonus, the table rows are varying in height.

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Xcode version (e.g. 9.1): ℹ9.2
- PopupDialog version (e.g. 0.5.0): ℹ0.7.0
- Minimum deployment target (e.g. 9.0): ℹ9.0
- Language (Objective-C / Swift): ℹSwift
- In case of Swift - Version (e.g. 4): ℹ4

## Dependency management
If you are not using any dependency managers, you can remove this section.

- Dependency manager (e.g. CocoaPods): ℹCocoaPods
- Version (e.g. 1.3.1): ℹ ? (just updated last week)

## What did you do?

ℹ Without special code or a predetermined height constraint a tableview won't show. My coworker and I have come up with a solution, but it needs tweaking for the iPhone X, so was wondering if I'm doing it wrong.  

## What did you expect to happen?

ℹ Not sure it should have done anything different, see above for a description. 

## What happened instead?

ℹ See above, without a height constraint the custom view doesn't show, just the buttons show.  

## Project that demonstrates the issue

ℹ Please let me know if this has piqued your interest and I'll put a demo together.

**Comment by mwfire** [comment]
Hey @kehollin, sorry for my late reply.
Yeah, that's true, custom view controllers have to define their height on its own at the moment. That is, also table views have to have a minimum height defined, otherwise you won't see them, independently of their content size. One example of this can be found here: https://github.com/mwfire/PopupDialogCustomExample

If you have some ideas on how to improve this, I'd be more than happy to discuss this with you!

Cheers
Martin
