### ISSUE TITLE
How to change the position and size  of PopupDialogContainerView

### ISSUE THREAD

**Issue by hengchengfei** [Orderella/PopupDialog#238]
# Report

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Xcode version (e.g. 9.1): 9.4
- PopupDialog version (e.g. 0.5.0): 0.7.1
- Minimum deployment target (e.g. 9.0): 9.0
- Language (Objective-C / Swift): Swift
- In case of Swift - Version (e.g. 4): 4.1

- Dependency manager (e.g. CocoaPods): CocoaPods
- Version (e.g. 1.3.1): 1.4.0.beta.1

## What did you do?
1, The  PopupDialog View  showed at the bottom.
2, The PopupDialog View's Width == UIScreen.width

There are not custom properties in PopupDialogContainerView.appearance

## What did you expect to happen?
![001-](https://user-images.githubusercontent.com/3182964/41279123-2fe6d850-6e5e-11e8-976c-60424ba347a0.png)

**Comment by mwfire** [comment]
Hey @hengchengfei,

this is currently not possible with PopupDialog. In order to keep this as lightweight as possible, this feature was not implemented. In the meantime, https://github.com/IcaliaLabs/Presentr/tree/master/Presentr could be an option if you are looking for this specific kind of dialog.

Have a nice day :)
