### ISSUE TITLE
I can't call custom func inside Button declare

### ISSUE THREAD

**Issue by bootavo** [Orderella/PopupDialog#271]
Hi guys, I tried to call a custom fund inside button declare, but it wasn't possible, any ideas to do this?

![popupdialog](https://user-images.githubusercontent.com/14097065/45974641-8c8aa280-c007-11e8-82c7-b34246c5711a.png)

**Comment by mwfire** [comment]
This is more of a Swift related thing. As you are declaring the buttons as properties of the class, they don't have access to the scope of that class at the time of initialization. One thing that should work is using `lazy var` instead of `let`.

Having said that, I don't really see the benefits in reusing buttons. I'd recommend you always create and assign these buttons when you show the PopupDialog, just as in the example project.

Hope that makes sense :)
