### ISSUE TITLE
Ipad screen size

### ISSUE THREAD

**Issue by asuhasoft** [Orderella/PopupDialog#312]
How do we make the sizing according to ipad?

**Comment by maari2k23** [comment]
Yes. Thank you for your support. And, As per our scope we need to move for iPad itself. So please guide me how to resize the popup view. Thanks in advance.

**Comment by mwfire** [comment]
Hey there!

So far, the dialog width is automatically evaluated for phone size classes. This was originally to ensure smaller devices will also correctly display the dialog, by using margins from left & right rather than a fixed width. Preferred width currently can only be specified for tablets. Height is defined by the content, however.

What would be your favorite way of making this work across all device sizes? (Looking for inspiration)
