### ISSUE TITLE
Issue with completion handler not being called

### ISSUE THREAD

**Issue by nickthedude** [Orderella/PopupDialog#330]
# Report

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Xcode version (e.g. 9.1): 10.3
- PopupDialog version (e.g. 0.5.0): 1.0.0 and 1.1.0
- Minimum deployment target (e.g. 9.0): 11.4
- Language (Objective-C / Swift): swift
- In case of Swift - Version (e.g. 4): 5

## Dependency management
If you are not using any dependency managers, you can remove this section.

- Dependency manager (e.g. CocoaPods): pods
- Version (e.g. 1.3.1): 1.5.3

## What did you do?

I am presenting a viewcontroller without any buttons so the only way to dismiss is by either gesture or tapping off view.

## What did you expect to happen?

The completion block to be called
## What happened instead?

when dismiss was called on the popupdialog the completion was nil, it wasn't nil in the init function

**Comment by nickthedude** [comment]
Any help on this?

**Comment by nickthedude** [comment]
Looking at the code is it possible the completion handler member variable is ignored because the argument coming into the dismiss method being overridden has the same name?

**Comment by mwfire** [comment]
Hey there! Please excuse my late reply. Usually, when the completion handler is not called, it is due to a custom view controller that is not deinitialized. Can you confirm?

**Comment by nick-iCars** [comment]
It's definitely a custom view controller. Not sure im understanding about deinitialization.  It was presented, now being dismissed, are you saying something is retaining a reference or something?

**Comment by mwfire** [comment]
The completion handler is called once the dialog was deinitialized. 
https://github.com/Orderella/PopupDialog/blob/30ffc27a2727f91aeaff737d4cd667f0b37fa5f9/PopupDialog/Classes/PopupDialog.swift#L220-L223

I am still thinking about moving this back to the real dismissal, on the other hand you know there is a retain cycle if the completion handler is not called. This could be due to strong references in one of the button actions or completion handler. If you are referring to the dialog or the view controller in one of these, make sure to use weak references, e.g.

```swift
button.action = { [weak dialog] in
  dialog?.doSomething()
}
```

Does that help?

**Comment by nickthedude** [comment]
I’ll give it a go
