### ISSUE TITLE
Customize TransitionAnimator / TransitionAnimations

### ISSUE THREAD

**Issue by andrewcl** [Orderella/PopupDialog#53]
As of version 0.5.0 the TransitionAnimator subclasses defined in TransitionAnimations are set as final internal classes. The inDuration and outDuration parameters of the TransitionAnimator subclasses are defined in the init method and are hardcoded into the project. The hardcoded values approach prevents configuration of both the inDuration and outDuration parameters. This leaves users of PopupDialog with the choice of either forking the project in order to update the duration properties, or accept the baked in values. 

Are there plans to make the TransitionAnimator subclasses configurable?

**Comment by andrewcl** [comment]
Are there any plans to make animations configurable in PopupDialog beyond the default animation options?

**Comment by mwfire** [comment]
@andrewcl Initially, the idea was to set animation times via the enums associated values. However, Objective-C compatibility was a strongly requested feature, and these do not bridge. Even more so, we added many user requested features which will require a configuration object instead of parameters. With the next version iteration, I consider adding this, so this is where animation durations could make it to the release.

To speed things up a bit: do you have the time to do a pull request for this feature?

Thanks and have a nice day!
