### ISSUE TITLE
Closing the PopUp using custom control on the ViewController

### ISSUE THREAD

**Issue by ghost** [Orderella/PopupDialog#66]
I have a custom view controller which implements a custom button to carry out events.  Once these events are complete, I would like to close the popup but I can't find a way of accessing the handleClose method of the PopupDialog (in fact I can't find a away to reference the PopupDialog from within the custom view controller), is there a way to do this without extending the PopupDialog?

The ideal scenario would be the ability to access the PopupDialog functions from the presented view controller.

**Comment by mwfire** [comment]
Hi @Collibhoy!

This question comes up frequently and I will update the docs (and the example app) on this soon.
Please find below the modified example app. It dismisses the dialog automatically once the rating is less or equal two stars. The idea is to pass your custom view controller a reference to the PopupDialog it is contained in. Make sure it is a weak variable in order to avoid retain cycles.

```
class RatingViewController: UIViewController {

    @IBOutlet weak var cosmosStarRating: CosmosView!

    @IBOutlet weak var commentTextField: UITextField!
    
    // Reference to the Popup dialog which
    // contains this view controller. Make
    // sure it is a weak reference to avoid
    // retain cycles
    weak var dialog: PopupDialog? = nil

    override func viewDidLoad() {
        super.viewDidLoad()

        commentTextField.delegate = self
        view.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(endEditing)))
        
        // Close the dialog if rating is less or equal 2
        cosmosStarRating.didTouchCosmos = { [weak self] rating in
            if rating <= 2 {
                self?.dialog?.dismiss()
            }
        }
    }
}
```

The dialog is now passed to the custom view controller.

```
// Create a custom view controller
let ratingVC = RatingViewController(nibName: "RatingViewController", bundle: nil)

// Create the dialog
let popup = PopupDialog(viewController: ratingVC, buttonAlignment: .horizontal, transitionStyle: .bounceDown, gestureDismissal: true)
        
// Pass a reference to the dialog
ratingVC.dialog = popup
...
```

Hope that helps :)

Cheers,
Martin

**Comment by mwfire** [comment]
Please find more on this at #80
